include:
  project: TankerHQ/gitlab-ci-files
  file: /native.yml
  ref: theo/fix_native_workflow_rules

###############
# build stage #
###############

build/linux:
  extends:
    - .build
    - .tags/linux
    - .rules/mr/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release

build/linux/shared:
  extends:
    - .build
    - .tags/linux
    - .rules/mr/manual
    - .before-script/bump-files-on-release/bash
    - .build-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release-shared

build/windows:
  extends:
    - .build
    - .tags/windows
    - .rules/mr/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/powershell
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile vs2019-release

build/macos:
  extends:
    - .build
    - .tags/macos
    - .rules/mr/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/macos/shared:
  extends:
    - .build
    - .tags/macos
    - .rules/mr/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release-shared

build/android:
  extends:
    - .build
    - .tags/linux
    - .rules/mr/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile android-armv7-release --profile android-armv8-release --profile android-x86-release --profile android-x86_64-release --profile gcc8-release-shared

build/ios:
  extends:
    - .build
    - .tags/macos
    - .rules/mr/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile ios-x86-release --profile ios-x86_64-release --profile ios-armv7-release --profile ios-armv7s-release --profile ios-armv8-release

nightly/coverage:
  extends:
    - .build
    - .tags/linux
    - .rules/nightly
  script:
    # Using gcc8-release profile, but CI script will force debug for Tanker only
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release --coverage
    - mv build/gcc8-release/coverage coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

######################
# bridge-check stage #
######################

bridge/ios:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/ios
  variables:
    UPSTREAM_RUNNER_TAG: macos
    UPSTREAM_JOB_NAME: build/ios
  trigger:
    project: TankerHQ/sdk-ios
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/android:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/android
  variables:
    UPSTREAM_RUNNER_TAG: linux
    UPSTREAM_JOB_NAME: build/android
  trigger:
    project: TankerHQ/sdk-android
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/python/linux:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/linux
  variables:
    UPSTREAM_RUNNER_TAG: linux
    UPSTREAM_JOB_NAME: build/linux
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/python/macos:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/macos
  variables:
    UPSTREAM_RUNNER_TAG: macos
    UPSTREAM_JOB_NAME: build/macos
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/python/windows:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/windows
  variables:
    UPSTREAM_RUNNER_TAG: windows
    UPSTREAM_JOB_NAME: build/windows
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/ruby/linux:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/linux/shared
  variables:
    UPSTREAM_RUNNER_TAG: linux
    UPSTREAM_JOB_NAME: build/linux/shared
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/ruby/macos:
  extends:
    - .bridge-check
    - .rules/bridge-ci
    - .variables/bridge-common
  needs:
    - build/macos/shared
  variables:
    UPSTREAM_RUNNER_TAG: macos
    UPSTREAM_JOB_NAME: build/macos/shared
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: theo/conan_alias

###############
# check stage #
###############

check/compat:
  extends:
    - .check
    - .tags/linux
    - .rules/mr/auto
    - .before-script/bump-files-on-release/bash
  needs:
    - build/linux
  script:
    - poetry run python compat/run-compat.py --profile gcc8-release

check/e2e:
  extends:
    - .check
    - .tags/linux
    - .rules/mr/auto
    - .before-script/bump-files-on-release/bash
  image: registry.gitlab.com/tankerhq/ci/ci-main:latest
  needs:
    - build/linux
  script:
    - poetry run python end2end.py --isolate-conan-user-home --use-tanker=upstream --profile gcc8-release

################
# deploy stage #
################

deploy:
  extends:
    - .deploy
    - .tags/linux
    - .rules/deploy/native
  release:
    description: sdk-native v$SDK_NATIVE_RELEASE_VERSION
    tag_name: v$SDK_NATIVE_RELEASE_VERSION
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

pages:
  extends:
    - .deploy
    - .tags/linux
    - .rules/nightly
  needs:
    - nightly/coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days

#######################
# bridge-deploy stage #
#######################

bridge/ios/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/ios
    - .variables/bridge-common
  needs:
    - bridge/ios
    - deploy
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_IOS_RELEASE_VERSION: $SDK_IOS_RELEASE_VERSION
  trigger:
    project: TankerHQ/sdk-ios
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/android/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/android
    - .variables/bridge-common
  needs:
    - bridge/android
    - deploy
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_ANDROID_RELEASE_VERSION: $SDK_ANDROID_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-android
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/python/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/python
    - .variables/bridge-common
  needs:
    - deploy
    - bridge/python/windows
    - bridge/python/macos
    - bridge/python/linux
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_PYTHON_RELEASE_VERSION: $SDK_PYTHON_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: theo/conan_alias

bridge/ruby/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/ruby
    - .variables/bridge-common
  needs:
    - deploy
    - bridge/ruby/macos
    - bridge/ruby/linux
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_RUBY_RELEASE_VERSION: $SDK_RUBY_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: theo/conan_alias

################
# mirror stage #
################

mirror:
  extends:
    - .mirror
    - .tags/linux
    - .rules/mirror
  dependencies: []
  script:
    - poetry run python run-ci.py mirror
