before_script:
 - dmenv install

stages:
  - build
  - check
  - deploy

.build:
  stage: build
  except:
    - schedules
  artifacts:
    expire_in: 1 day
    paths:
      - build/

build/linux:
  extends: .build
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release

build/macos:
  extends: .build
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/windows:
  extends: .build
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --profile vs2017-release


.deploy:
  stage: deploy
  except:
    - schedules
  when: manual
  only:
    - tags

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home deploy

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py deploy

nightly/android:
  image: tanker.local:5000/ci-android:latest
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home nightly
  tags:
    - linux

nightly/ios:
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home nightly
  tags:
    - macos

nightly/emscripten:
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home nightly-build-emscripten
  tags:
    - linux

coverage:
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-debug --coverage
    - mv build/gcc8-debug/coverage coverage
  tags:
    - linux
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run -- python run-ci.py  mirror

check/compat:
  stage: check
  dependencies:
    - build/linux
  except:
    - master
  script:
    - dmenv run -- python compat/run-compat.py --isolate-conan-user-home --profile gcc8-release
  tags:
    - linux

check/e2e:
  stage: check
  dependencies:
    - build/linux
  script:
    - dmenv run -- python run-ci.py --isolate-conan-user-home e2e
  tags:
    - linux
  except:
    - tags
