image: tanker.local:5000/ci-cpp:latest

before_script:
 - dmenv install

stages:
  - deploy

.deploy:
  stage: deploy
  except:
    - schedules
  when: manual
  only:
    - tags

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - dmenv run -- python run-ci.py deploy

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - dmenv run -- python run-ci.py deploy

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - dmenv run -- python run-ci.py deploy


pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
