before_script:
 - poetry install

stages:
  - build
  - check
  - deploy

.build:
  stage: build
  except:
    - schedules

build/linux:
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - package/
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release

build/macos:
  extends: .build
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/windows/visual:
  extends: .build
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile vs2019-release

build/windows/mingw:
  extends: .build
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile mingw32-release


.deploy:
  stage: deploy
  except:
    - schedules
  when: manual
  only:
    - tags

deploy/linux:
  extends: .deploy
  tags: [linux]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

deploy/macos:
  extends: .deploy
  tags: [macos]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

deploy/windows:
  extends: .deploy
  tags: [windows]
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

nightly/coverage:
  stage: build
  only:
    - schedules
  script:
    # Using gcc8-release profile, but CI script will force debug for Tanker only
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release --coverage
    - mv build/gcc8-release/coverage coverage
  tags:
    - linux
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - nightly/coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags
    - master
    - /\Afeat\/.+\z/   # feat/ branches
  except:
    - schedules
  script:
    - poetry run python run-ci.py  mirror

check/compat:
  stage: check
  dependencies:
    - build/linux
  except:
    - master
  script:
    - poetry run python compat/run-compat.py --isolate-conan-user-home --profile gcc8-release
  tags:
    - linux

check/e2e:
  stage: check
  dependencies:
    - build/linux
  script:
    - poetry run python end2end.py --isolate-conan-user-home --profile gcc8-release
  tags:
    - linux
