image: tanker.local:5000/ci-native:latest

before_script:
 - poetry install

stages:
  - build
  - bridge
  - check
  - deploy
  - mirror

workflow:
  rules:
    # web pipelines for releases
    - if: $CI_PIPELINE_SOURCE == "web" && ($SDK_NATIVE_RELEASE_VERSION != null && $SDK_NATIVE_RELEASE_VERSION !~ /\A[0-9.]+(-[a-z]+[0-9]+)?\z/)
      when: never
    # allow everything else
    - when: always

.build-always:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
      # trigger the job after a MR is merged on feature branches and master
      # $CI_MERGE_REQUEST_ID == null is needed to avoid duplicate pipelines
    - if: $CI_MERGE_REQUEST_ID == null && $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME =~ /\Afeat\/.+\z/)
    - if: $CI_PIPELINE_SOURCE == "schedule"

.build-manual:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_NATIVE_RELEASE_VERSION

build/linux:
  extends: .build-always
  artifacts:
    expire_in: 1 day
    paths:
      - package/
  tags: [linux]
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release

build/android:
  extends: .build-manual
  artifacts:
    paths:
      - package/
  tags: [linux]
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile android-armv7-release --profile android-armv8-release --profile android-x86-release --profile android-x86_64-release --profile gcc8-release-shared

build/linux/shared:
  extends: .build-manual
  artifacts:
    paths:
      - package/
  tags: [linux]
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release-shared

build/macos:
  extends: .build-always
  artifacts:
    paths:
      - package
  tags: [macos]
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release

build/macos/shared:
  extends: .build-manual
  artifacts:
    paths:
      - package/
  tags: [macos]
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile macos-release-shared

build/ios:
  extends: .build-manual
  tags: [macos]
  artifacts:
    paths:
      - package
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile ios-x86-release --profile ios-x86_64-release

build/windows/visual:
  extends: .build-always
  tags: [windows]
  artifacts:
    paths:
      - package
  script:
    - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile vs2019-release

# build/windows/mingw:
#   extends: .build-manual
#   tags: [windows]
#   script:
#     - if [ ! -z $SDK_NATIVE_RELEASE_VERSION ]; then poetry run python run-ci.py bump-files --version=$SDK_NATIVE_RELEASE_VERSION ; fi
#     - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile mingw32-release

deploy:
  stage: deploy
  tags: [linux]
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $SDK_NATIVE_RELEASE_VERSION
      when: manual
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy
  release:
    tag_name: v$SDK_NATIVE_RELEASE_VERSION
    description: sdk-native release v$SDK_NATIVE_RELEASE_VERSION

nightly/coverage:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    # Using gcc8-release profile, but CI script will force debug for Tanker only
    - poetry run python run-ci.py --isolate-conan-user-home build-and-test --profile gcc8-release --coverage
    - mv build/gcc8-release/coverage coverage
  tags:
    - linux
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

bridge/ios:
  needs: ["build/ios"]
  stage: bridge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: macos
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/ios
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-ios
    strategy: depend

bridge/android:
  needs: ["build/android"]
  stage: bridge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: linux
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/android
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-android
    strategy: depend

bridge/ruby/linux:
  needs: ["build/linux/shared"]
  stage: bridge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: linux
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/linux/shared
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-ruby
    strategy: depend

bridge/ruby/macos:
  needs: ["build/macos/shared"]
  stage: bridge
  rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: macos
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/macos/shared
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-ruby
    strategy: depend

bridge/python/macos:
  needs: ["build/macos"]
  stage: bridge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: macos
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/macos
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-python
    strategy: depend

bridge/python/linux:
  needs: ["build/linux"]
  stage: bridge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: linux
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/linux
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-python
    strategy: depend

bridge/python/windows:
  needs: ["build/windows/visual"]
  stage: bridge
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  variables:
    UPSTREAM_RUNNER_TAG: windows
    UPSTREAM_PROJECT_ID: $CI_PROJECT_ID
    UPSTREAM_PIPELINE_ID: $CI_PIPELINE_ID
    UPSTREAM_JOB_NAME: build/windows/visual
    UPSTREAM_BRANCH_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: tanker/sdk-python
    strategy: depend

pages:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  dependencies:
    - nightly/coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /\Av[0-9.]+\z/
    - if: $CI_COMMIT_REF_NAME =~ /\Afeat\/.+\z/
    - if: $CI_COMMIT_REF_NAME == "master"
  script:
    - poetry run python run-ci.py mirror

check/compat:
  stage: check
  needs: ["build/linux"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  script:
    - poetry run python compat/run-compat.py --isolate-conan-user-home --profile gcc8-release
  tags:
    - linux

check/e2e:
  image: tanker.local:5000/ci-base:latest
  stage: check
  needs: ["build/linux"]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"
  script:
    - poetry run python end2end.py --isolate-conan-user-home --profile gcc8-release
  tags:
    - linux
