image: tanker.local:5000/ci-cpp:latest

before_script:
 - dmenv install
 - export PATH=$(dmenv show:venv_path)/bin:$PATH

stages:
  - build
  - deploy

build/linux:
  stage: build
  except:
    - schedules
  tags:
    - linux
  script:
    - dmenv run -- python run-ci.py build-and-test --profile gcc8
  cache:
    paths:
      - build

deploy/linux:
  stage: deploy
  except:
    - schedules
  when: manual
  tags:
    - linux
  only:
    - tags
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py deploy --profile android --git-tag ${CI_COMMIT_TAG}
  cache:
    paths:
      - build

build/macos:
  stage: build
  except:
    - schedules
  tags:
    - macos
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py build-and-test --profile macos

deploy/macos:
  stage: deploy
  except:
    - schedules
  when: manual
  tags:
    - macos
  only:
    - tags
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py deploy --profile ios --git-tag ${CI_COMMIT_TAG}

nightly/android:
  image: tanker.local:5000/ci-android:latest
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py nightly
  tags:
    - linux

nightly/ios:
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py nightly
  tags:
    - macos

nightly/emscripten:
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py build-and-test --profile emscripten
  tags:
    - linux

coverage:
  stage: build
  only:
    - schedules
  script:
    - dmenv run -- python run-ci.py clean-cache
    - dmenv run -- python run-ci.py build-and-test --profile gcc8 --coverage
    - mv build/gcc8/x86_64/Release/coverage coverage
  tags:
    - linux
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

pages:
  stage: deploy
  only:
    - schedules
  dependencies:
    - coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days
  tags:
    - linux

mirror:
  tags:
    - linux
  stage: deploy
  only:
    - /\Av[0-9.]+\z/   # public release tags only
    - master
  except:
    - schedules
  script:
    - dmenv run python run-ci.py mirror
