include:
  project: TankerHQ/gitlab-ci-files
  file: /native.yml
  ref: 2021-11-10-229

.after-script/branch_name:
  after_script:
    - echo $CI_COMMIT_REF_NAME > branch_name.txt

###############
# build stage #
###############

.rules/build/manual:
  rules:
    - !reference [.rules/mr/manual, rules]
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/nightly, rules]
    - !reference [.rules/push-master, rules]

.rules/build/auto:
  rules:
    - !reference [.rules/mr/auto, rules]
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/nightly, rules]
    - !reference [.rules/push-master-or-feat, rules]

build/linux:
  extends:
    - .build
    - .tags/linux
    - .rules/build/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile linux-release

build/linux/shared:
  extends:
    - .build
    - .tags/linux
    - .rules/build/auto
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
    - .build-artifacts
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile linux-release-shared

build/windows:
  extends:
    - .build
    - .tags/windows
    - .rules/build/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/powershell
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile vs2019-release

build/windows/shared:
  extends:
    - .build
    - .tags/windows
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/powershell
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile vs2019-release-shared

build/macos/x86_64:
  extends:
    - .build
    - .tags/macos/x86_64
    - .rules/build/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile macos-x86_64-release

build/macos/arm:
  extends:
    - .build
    - .tags/macos/arm
    - .rules/build/auto
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile macos-armv8-release

build/macos/x86_64/shared:
  extends:
    - .build
    - .tags/macos/x86_64
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile macos-x86_64-release-shared

build/macos/arm/shared:
  extends:
    - .build
    - .tags/macos/arm
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile macos-armv8-release-shared

build/android/shared:
  extends:
    - .build
    - .tags/linux
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile android-armv7-release --profile android-armv8-release --profile android-x86-release --profile android-x86_64-release --profile linux-release-shared

build/android/static/http-backend:
  extends:
    - .build
    - .tags/linux
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile android-armv7-release-static-http_backend --profile android-armv8-release-static-http_backend --profile android-x86-release-static-http_backend --profile android-x86_64-release-static-http_backend

build/ios:
  extends:
    - .build
      # build everything on the fast one
    - .tags/macos/arm
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile ios-simulator-armv8-release --profile ios-simulator-x86-release --profile ios-simulator-x86_64-release --profile ios-armv7-release --profile ios-armv7s-release --profile ios-armv8-release

build/ios/http-backend:
  extends:
    - .build
      # build everything on the fast one
    - .tags/macos/arm
    - .rules/build/manual
    - .build-artifacts
    - .before-script/bump-files-on-release/bash
    - .after-script/branch_name
  script:
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile ios-simulator-armv8-release-http_backend --profile ios-simulator-x86-release-http_backend --profile ios-simulator-x86_64-release-http_backend --profile ios-armv7-release-http_backend --profile ios-armv7s-release-http_backend --profile ios-armv8-release-http_backend

nightly/coverage:
  extends:
    - .build
    - .tags/linux
    - .rules/nightly
  script:
    # Using linux-release profile, but CI script will force debug for Tanker only
    - poetry run python run-ci.py --isolate-conan-user-home build --test --profile linux-release --coverage
    - mv build/linux-release/coverage coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 7 days

######################
# bridge-check stage #
######################

.rules/bridge/auto:
  rules:
    - !reference [.rules/mr/auto, rules]
    - !reference [.rules/web/auto, rules]
    - !reference [.rules/push-master, rules]

.rules/bridge/manual:
  rules:
    - !reference [.rules/mr/manual, rules]
    - !reference [.rules/web/auto, rules]

bridge/bench/linux:
  stage: bridge-check
  extends:
    - .variables/bridge-common
  rules:
    - !reference [.rules/mr/manual, rules]
  needs:
    - build/linux
    - build/linux/shared
  variables:
    UPSTREAM_JOB_NAME: build/linux:build/linux/shared
    UPSTREAM_JOB_TARGET: linux
    UPSTREAM_MERGE_REQUEST_IID: $CI_MERGE_REQUEST_IID
    UPSTREAM_COMMIT_SHA: $CI_COMMIT_SHA
    UPSTREAM_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME
  trigger:
    project: TankerHQ/benchmarks
    strategy: depend

bridge/compat/linux:
  stage: bridge-check
  extends:
    - .rules/bridge/auto
    - .variables/bridge-common
  needs:
    - build/linux
  variables:
    UPSTREAM_JOB_NAME: build/linux
    UPSTREAM_JOB_TARGET: linux
  trigger:
    project: TankerHQ/compatibility-tests
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/ios:
  stage: bridge-check
  extends:
    - .rules/bridge/auto
    - .variables/bridge-common
  needs:
    - build/ios
  variables:
    UPSTREAM_JOB_NAME: build/ios
  trigger:
    project: TankerHQ/sdk-ios
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/android:
  extends:
    - .bridge-check
    - .rules/bridge/auto
    - .variables/bridge-common
  needs:
    - build/android/shared
  variables:
    UPSTREAM_JOB_NAME: build/android/shared
  trigger:
    project: TankerHQ/sdk-android
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/linux:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/linux
  variables:
    UPSTREAM_JOB_TARGET: linux
    UPSTREAM_JOB_NAME: build/linux
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/windows:
  extends:
    - .bridge-check
    - .rules/bridge/auto
    - .variables/bridge-common
  needs:
    - build/windows/shared
  variables:
    UPSTREAM_JOB_TARGET: windows
    UPSTREAM_JOB_NAME: build/windows/shared
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/ios:
  extends:
    - .bridge-check
    - .rules/bridge/auto
    - .variables/bridge-common
  needs:
    - build/ios/http-backend
  variables:
    UPSTREAM_JOB_TARGET: ios
    UPSTREAM_JOB_NAME: build/ios/http-backend
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/macos/x86_64:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/macos/x86_64
  variables:
    UPSTREAM_JOB_TARGET: macos-x86_64
    UPSTREAM_JOB_NAME: build/macos/x86_64
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/macos/arm:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/macos/arm
  variables:
    UPSTREAM_JOB_TARGET: macos-arm
    UPSTREAM_JOB_NAME: build/macos/arm
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/android:
  extends:
    - .bridge-check
    - .rules/bridge/auto
    - .variables/bridge-common
  needs:
    - build/android/static/http-backend
  variables:
    UPSTREAM_JOB_TARGET: android
    UPSTREAM_JOB_NAME: build/android/static/http-backend
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/python/linux:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/linux
  variables:
    UPSTREAM_JOB_TARGET: linux
    UPSTREAM_JOB_NAME: build/linux
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/python/macos/x86_64:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/macos/x86_64
  variables:
    UPSTREAM_JOB_TARGET: macos-x86_64
    UPSTREAM_JOB_NAME: build/macos/x86_64
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/python/macos/arm:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/macos/arm
  variables:
    UPSTREAM_JOB_TARGET: macos-arm
    UPSTREAM_JOB_NAME: build/macos/arm
    UPSTREAM_JOB_ARCH: arm
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/python/windows:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/windows
  variables:
    UPSTREAM_JOB_TARGET: windows
    UPSTREAM_JOB_NAME: build/windows
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/ruby/linux:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/linux/shared
  variables:
    UPSTREAM_JOB_TARGET: linux
    UPSTREAM_JOB_NAME: build/linux/shared
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/ruby/macos/x86_64:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/macos/x86_64/shared
  variables:
    UPSTREAM_JOB_TARGET: macos-x86_64
    UPSTREAM_JOB_NAME: build/macos/x86_64/shared
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/ruby/macos/arm:
  extends:
    - .bridge-check
    - .rules/bridge/manual
    - .variables/bridge-common
  needs:
    - build/macos/arm/shared
  variables:
    UPSTREAM_JOB_TARGET: macos-arm
    UPSTREAM_JOB_NAME: build/macos/arm/shared
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: feat/storage

###############
# check stage #
###############

.rules/check:
  rules: !reference [.rules/build/auto, rules]

check/e2e:
  extends:
    - .check
    - .tags/linux
    - .rules/check
    - .before-script/bump-files-on-release/bash
  image: registry.gitlab.com/tankerhq/docker/e2e:latest
  needs:
    - build/linux
  script:
    - poetry run python end2end.py --isolate-conan-user-home --use-tanker=upstream --profile linux-release

################
# deploy stage #
################

deploy:
  extends:
    - .deploy
    - .tags/linux
    - .rules/deploy/native
  release:
    description: sdk-native v$SDK_NATIVE_RELEASE_VERSION
    tag_name: v$SDK_NATIVE_RELEASE_VERSION
  script:
    - poetry run python run-ci.py --isolate-conan-user-home deploy

pages:
  extends:
    - .deploy
    - .tags/linux
    - .rules/nightly
  needs:
    - nightly/coverage
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 7 days

#######################
# bridge-deploy stage #
#######################

bridge/ios/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/ios
    - .variables/bridge-common
  needs:
    - bridge/ios
    - deploy
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_IOS_RELEASE_VERSION: $SDK_IOS_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-ios
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/android/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/android
    - .variables/bridge-common
  needs:
    - bridge/android
    - deploy
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_ANDROID_RELEASE_VERSION: $SDK_ANDROID_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-android
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/python/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/python
    - .variables/bridge-common
  needs:
    - deploy
    - bridge/python/windows
    - bridge/python/macos/x86_64
    - bridge/python/macos/arm
    - bridge/python/linux
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_PYTHON_RELEASE_VERSION: $SDK_PYTHON_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-python
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/ruby/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/ruby
    - .variables/bridge-common
  needs:
    - deploy
    - bridge/ruby/macos/x86_64
    - bridge/ruby/macos/arm
    - bridge/ruby/linux
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_RUBY_RELEASE_VERSION: $SDK_RUBY_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-ruby
    strategy: depend
    # FIXME
    branch: feat/storage

bridge/rust/deploy:
  extends:
    - .bridge-deploy
    - .rules/bridge-release/rust
    - .variables/bridge-common
  needs:
    - deploy
    - bridge/rust/ios
    - bridge/rust/android
    - bridge/rust/macos/arm
    - bridge/rust/macos/x86_64
    - bridge/rust/linux
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_RUST_RELEASE_VERSION: $SDK_RUST_RELEASE_VERSION
    SDK_NATIVE_LATEST_CONAN_REFERENCE: tanker/$SDK_NATIVE_RELEASE_VERSION@
  trigger:
    project: TankerHQ/sdk-rust
    strategy: depend
    # FIXME
    branch: feat/storage

#############################
# react-native-deploy stage #
#############################

bridge/react-native/deploy:
  extends:
    - .react-native-deploy
    - .rules/bridge-release/react-native
    - .variables/bridge-common
  needs:
    - bridge/android/deploy
    - bridge/ios/deploy
  variables:
    UPSTREAM_BRIDGE_STAGE: deploy
    SDK_ANDROID_RELEASE_VERSION: $SDK_ANDROID_RELEASE_VERSION
    SDK_IOS_RELEASE_VERSION: $SDK_IOS_RELEASE_VERSION
    SDK_REACT_NATIVE_RELEASE_VERSION: $SDK_REACT_NATIVE_RELEASE_VERSION
  trigger:
    project: TankerHQ/sdk-react-native
    strategy: depend
    # FIXME
    branch: feat/storage
